Repository UBC-MDS/Student_Living_Guide, pull requests merged in 2023-02, with the labels that each got.

#17 add contribution and CoC documentation
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation

#16 Add Shiny app template
  .gitignore
  Student_Living_Guide_Shiny/Student_Living_Guide_Shiny.Rproj
  Student_Living_Guide_Shiny/app.R
  Student_Living_Guide_Shiny/server/tab1.R
  Student_Living_Guide_Shiny/ui/tab1.R
Labels: development

#15 Data preprocessing
  README.md
  data/processed_data.csv
  data/raw_data.csv
  requirements.txt
  src/preprocessing.py
Labels: documentation, development

#13 adding sketch
  img/sketch.png
Labels: design

#19 add EDA notebook
  EDA.ipynb
  README.md
Labels: documentation, development

#20 Adding proposal sections
  reports/proposal.md
Labels: documentation

#21 update sketch (sidebar)
  img/sketch.png
Labels: enhancement

#23 fix typo & update wordings
  README.md
  reports/proposal.md
Labels: documentation, enhancement
