Repository UBC-MDS/Student_Living_Guide, pull requests merged in 2023-03, with the labels that each got.

#41 Map development & Layout Update
  Student_Living_Guide_Shiny/app.R
  Student_Living_Guide_Shiny/server/tab1.R
  Student_Living_Guide_Shiny/ui/tab1.R
Labels: development

#42 upload reflection-milestone2.md & add map plot related content
  doc/reflection-milestone2.md
Labels: documentation

#71 Set default country as United States
  Student_Living_Guide_Shiny/app.R
  Student_Living_Guide_Shiny/server/tab1.R
Labels: development

#72 Added download button
  Student_Living_Guide_Shiny/app.R
  Student_Living_Guide_Shiny/server/tab1.R
Labels: enhancement

#75 Deployment workflow
  .github/workflows/deploy-app.yaml
  .github/workflows/testing.yaml
  renv.lock
  renv/.gitignore
  renv/activate.R
  renv/settings.json
Labels: deployment

#79 Updated readme app demo
  README.md
Labels: documentation

#78 Testthat subplots
  .Rprofile
  app.R
  renv.lock
  tests/testthat.R
  tests/testthat/_snaps/shinytest2/dist_scatter_NA-001.json
  tests/testthat/_snaps/shinytest2/dist_scatter_NA-001_.png
  tests/testthat/_snaps/shinytest2/dist_scatter_asia_armenia-001.json
  tests/testthat/_snaps/shinytest2/dist_scatter_asia_armenia-001_.png
  tests/testthat/_snaps/shinytest2/dist_scatter_europe_austria-001.json
  tests/testthat/_snaps/shinytest2/dist_scatter_europe_austria-001_.png
  tests/testthat/setup-shinytest2.R
  tests/testthat/test-shinytest2.R
Labels: deployment

#82 adding a spinner for map plot
  app.R
Labels: enhancement, development

#83 add reflection for milestone 4
  doc/reflection-milestone4.md
Labels: documentation
